# Generated by Django 4.0.3 on 2022-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptorInfopage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=200)),
                ('ContactNumber', models.CharField(max_length=11)),
                ('EmailAddress', models.CharField(max_length=80)),
                ('Age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfAdoption', models.DateField(max_length=11)),
                ('ReasonOfAdoption', models.CharField(max_length=11)),
                ('Household', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='DogList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DogName', models.CharField(max_length=11)),
                ('DogGender', models.CharField(max_length=11)),
                ('DogBreed', models.CharField(max_length=11)),
                ('DogAge', models.CharField(max_length=11)),
                ('DogFurColor', models.CharField(max_length=11)),
            ],
        ),
    ]
