# Generated by Django 4.0.3 on 2022-07-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enimalproj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DateField(max_length=20)),
                ('DateTransaction', models.DateField(max_length=11)),
                ('Message', models.TextField(default='')),
                ('Status', models.DateField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('ContactNumber', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=2)),
                ('EmailAddress', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='AdoptorInfopage',
        ),
        migrations.RenameField(
            model_name='dogadoption',
            old_name='DateOfAdoption',
            new_name='DateToAdopt',
        ),
        migrations.RenameField(
            model_name='dogadoption',
            old_name='Household',
            new_name='Remarks',
        ),
        migrations.RenameField(
            model_name='doglist',
            old_name='DogAge',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='doglist',
            old_name='DogBreed',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='doglist',
            old_name='DogFurColor',
            new_name='fur',
        ),
        migrations.RenameField(
            model_name='doglist',
            old_name='DogGender',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='ReasonOfAdoption',
        ),
        migrations.RemoveField(
            model_name='doglist',
            name='DogName',
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='DateToday',
            field=models.DateField(default='exit', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogdonation',
            name='aId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enimalproj.registration'),
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='aId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enimalproj.registration'),
        ),
    ]
